#! /bin/sh
### BEGIN INIT INFO
# Provides:          home-node
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     4 5
# Default-Stop:      0 1 2 3 6
# Short-Description: Starts the home node daemon.
# Description:       Starts the home node daemon.
### END INIT INFO

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"
DAEMON=/home/daddy/home-node/bin/home-node
LOGFILE=home/daddy/home-node.log
PIDFILE=/run/home-node.pid

case "$1" in
  start)
	log_daemon_msg "Starting home-node service" "home-node" || true
	if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --startas /bin/bash -- -c "exec $DAEMON > $LOGFILE 2>&1"; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;
  stop)
	log_daemon_msg "Stopping home-node service" "home-node" || true
	if start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  restart)
	log_daemon_msg "Restarting home-node service" "home-node" || true
	start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
	if start-stop-daemon --start --quiet --oknodo --background --make-pidfile --pidfile $PIDFILE --startas /bin/bash -- -c "exec $DAEMON > $LOGFILE 2>&1"; then
	    log_end_msg 0 || true
	else
	    log_end_msg 1 || true
	fi
	;;

  status)
	status_of_proc -p $PIDFILE $DAEMON home-node && exit 0 || exit $?
	;;

  *)
	log_action_msg "Usage: /etc/init.d/home-node {start|stop|restart|status}" || true
	exit 1
esac

exit 0
